title: Lorenzo Stella
show_downloads: false
google_analytics: 'UA-79741121-1'

author:
  email: lorenzostella<AT>gmail<DOT>com
  cv: /pdf/resume.pdf
  github: lostella
  twitter: lostella
  scholar: Y3ag8YsAAAAJ
  pic: /img/me.jpg
  pgp: /lostella.asc

permalink: /blog/:year/:month/:day/:title
