name: Lorenzo Stella
lang: en_US

author:
  name: Lorenzo Stella
  email: lorenzostella<AT>gmail<DOT>com
  cv: /pdf/cv-lorenzo-stella.pdf
  github: lostella
  twitter: lostella
  facebook: alletsol
  scholar: Y3ag8YsAAAAJ
  pgp: /lostella.asc

twitter:
  username: lostella
  card: summary

facebook:
  admins: alletsol

social:
  name: Lorenzo Stella
  links:
    - https://twitter.com/lostella
    - https://www.facebook.com/alletsol
    - https://github.com/lostella
    - https://keybase.io/lostella

google_analytics: 'UA-79741121-1'

permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
