title: Lorenzo Stella
show_downloads: false
google_analytics: 'UA-79741121-1'
theme:

author:
  email: lorenzostella<AT>gmail<DOT>com
  cv: /pdf/resume.pdf
  github: lostella
  twitter: lostella
  pic: /img/me.jpg
  pgp: /lostella.gpg

github:
  is_user_page: true
