title: Lorenzo Stella
show_downloads: false
google_analytics: 'UA-79741121-1'
theme:

author:
  email: lorenzostella@gmail.com
  cv: https://github.com/lostella/cv/raw/master/cv.pdf
  github: lostella

github:
  is_user_page: true
