baseURL = "https://lostella.github.io/"
languageCode = "en-us"
title = "Lorenzo Stella"
theme = "hugo-bearblog"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'friendly'
    tabWidth = 4
